config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [ :show ]
  root to: "pages#home"
  mount Attachinary::Engine => "/attachinary"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :locations, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:create, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :location
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/location.rb
class Location < ApplicationRecord
  # LOCATION = ["S'initier à l'agriculture urbaine", "Découvrir les bonnes pratiques à la campagne"]
  belongs_to :user
  has_many :bookings
  validates :address, presence: true
  # validates :urban, presence: true
  validates :capacity, presence: true
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  has_attachment :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attachment :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @location = Location.find(params[:location_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.location = @location
    @booking.address = @location.address

    # @booking = Booking.new(
    #   user_id: current_user.id;
    #   location_id: @location.id;
    #   address: @location.address;
    #   date_beginning: params[:date_beginning];
    #   date_end: params[:date_end])
    if @booking.save
      flash[:notice] = "Votre réservation a bien été prise en compte"
      redirect_to root_path
    else
      render "locations/show"
    end
  end

  def show
  end

  private

    def booking_params
      params.require(:booking).permit(:date_beginning, :date_end)
    end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!, only: :create

  def index
    if !params[:city].blank?
      @locations = Location.where(city: params[:city], urban: params[:urban], capacity: params[:capacity].to_i)
    else
      @locations = Location.all
      # @locations = Location.where(urban: params[:urban], capacity: params[:capacity].to_i)
    end
    @hash = Gmaps4rails.build_markers(@locations) do |location, marker|
      marker.lat location.latitude
      marker.lng location.longitude
    end
  end
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat

  def show
    @location = Location.find(params[:id])
    @hash = [{ lat: @location.latitude, lng: @location.longitude }]
    @booking = Booking.new(location_id: @location.id)
    @user = @location.user
  end
    #@Booking = Booking.new

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    @location.user = current_user
    if @location.save
      redirect_to location_path(@location)
    else
      render :new
    end
  end

  private
  def location_params
    params.require(:location).permit(:urban, :title, :address, :description, :capacity, :price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  #  @location = Location.new
  @locations = Location.all.sample(6)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GrowYourFood</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
  <!-- Add these line for detecting device width -->

  <%= yield %>

  <!-- [...] -->
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://maps.google.com/maps/api/js?key=#{ENV['google_browser_api_key']}" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
  <%= cloudinary_js_config %>

  <%= yield(:after_js) %>

  </body>

</html>

app/views/locations/index.html.erb
<div class="container">
  <div class="row">
  <!-- COL GAUCHE -->
    <div class="col-sx-12 col-md-7">
      <div class="row">
        <div class="col-xs-12">
          <div class="form-group paddedup">
            <h4 class="paddeddown">Vous avez choisi l'agriculture urbaine !</h4>
            <input type="text" class= "form-control" placeholder="Ville de votre choix" name="city">
          </div>
        <div class="form-group">
          <select name="capacity" id="capacity" class="form-control">
            <option value="1">1 participant</option>
            <option value="2" selected="selected">2 participants</option>
            <option value="3">3 participants</option>
            <option value="4">4 participants</option>
            <option value="5">5 participants</option>
            <option value="6">6 participants</option>
            <option value="7">7 participants</option>
            <option value="8">8 participants</option>
            <option value="9">9 participants</option>
            <option value="10">10 participants</option></select>
          </select>
        </div>
          <form action="/locations" method="get" class="form-inline">
            <button type="submit" class="btn btn-default">Street containers</button>
            <button type="submit" class="btn btn-default">Rooftop permaculture</button>
            <button type="submit" class="btn btn-default">Jardins partagés</button>
          </form>
        </div>
      </div>
      <% if @locations.empty? %>
        <p class="padded">Pas encore de stage correspondant à votre recherche :(</p>
      <% else %>
        <% @locations.each do |location |%>
            <div class="col-xs-12 col-md-6 padded">
              <%= render "shared/location_card", location: location %>
            </div>
        <% end %>
      <% end %>
    </div>
    <!-- COL DROITE -->
    <div class="col-xs-12 col-md-5 padded">
      <div id="map" style="position: absolute; left: 0px; top: 0px; z-index: 3; width: 100%; height: 100vh;" class="paddedup"></div>
        <% content_for(:after_js) do %>
          <%= javascript_tag do %>
            $(document).ready(function() {
              var handler = Gmaps.build('Google');
              handler.buildMap({ internal: { id: 'map' } }, function() {
                markers = handler.addMarkers(<%= raw @hash.to_json %>);
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
                if (markers.length == 0) {
                  handler.getMap().setZoom(2);
                } else if (markers.length == 1) {
                  handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>

      </div>
    </div>
</div>

app/views/locations/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6">
      <div class="new-location-container">
        <div class="new-location-header">
          <h1>Partagez votre savoir-faire!</h1>
          <p>Proposez un stage, chez vous, avec une technique que vous maîtrisez :)</p>
        </div>
        <div class="new-location-form padded">
          <%= simple_form_for @location do |f| %>
          <!-- Mettre type au lieu de urban une fois cree dans table -->
            <%# f.input :urban, label: "Agriculture urbaine // Techniques", as: :check_boxes, collection: ["Rooftop permaculture","Street container", "Jardins partagés"] %>
            <%= f.input :title, label: "Donnez un titre à votre stage", placeholder: "Collection de tomates à la Bourdaisière" %>
            <%= f.input :address, label: "Adresse", placeholder: "16 villa gaudelet, Paris"  %>
            <%= f.input :city, label: "Ville" %>
            <%= f.input :description, label: "Description", placeholder:"Quelques lignes pour décrire votre technique exceptionnelle" %>
            <%= f.input :capacity, label: "Capacité d'accueil", placeholder: "Combien de personnes pouvez-vous accueillir ?" %>
            <%= f.input :price, label: "Prix par jour", placeholder: "50 €" %>
            <%= f.input :photo, as: :attachinary %>
            <%= f.submit "Partager !", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="vertical-banner">
       &nbsp;
      </div>
    </div>
  </div>
</div>


 <!-- t.string   "address"
    t.text     "description"

    t.string   "urban"
    t.boolean  "rooftop"
    t.boolean  "permaculture"
    t.boolean  "training"

    t.integer  "capacity"
    t.integer  "price"
    t.datetime "created_at",   null: false
    t.datetime "updated_at",   null: false
    t.integer  "booking_id"
    t.integer  "user_id"
    t.string   "city"
    t.float    "latitude"
    t.float    "longitude"
    t.string   "title"
    t.float    "latitude"
    t.float    "longitude"
 -->

app/views/locations/reserve.html.erb
 <!-- formulaire de reservation -->
        <div class="index-form-container">
          <% if !current_user.host_game?(@game) %>
            <h2>Book this escape game</h2>
            <p> Réservez un temps d'apprentissage <
              <%= form_tag(new_game_booking_path(@game), :method => "get") do %>
                <div class="form-group">
                  <%= label_tag "date", "Booking date" %>
                  <%= text_field_tag :date, params[:date], placeholder: "Chose a date", class: "form-control border-radius datepicker" %>
                </div>
                <div class="form-group">
                  <%= label_tag "capacity", "Nombre de participants" %>
                  <% my_options_for_select_nb_players = (@game.min_players..@game.max_players).to_a.map { |x| [x.to_s + " players", x] } %>
                  <%= select_tag "nb_players", options_for_select(my_options_for_select_nb_players, params[:nb_players]), class: "form-control border-radius" %>
                </div>
                <div class="form-group">
                  <%= label_tag "time_select", "Available sessions" %>
                  <%= select_tag "time_select", options_for_select(@availabilities, params[:time_select]), class: "form-control border-radius" %>
                </div>
                <div class="form-group">
                  <%= label_tag "duration" %>
                  <% my_options_for_select_duration = (1..3).to_a.map { |x| [x.to_s + " hour(s)", x] } %>
                  <%= select_tag "duration", options_for_select(my_options_for_select_duration, params[:duration]), class: "form-control border-radius" %>
                </div>
                <button type="submit" class="btn btn-danger">Book</button>
              <% end %>
            </p>

app/views/locations/show.html.erb
<!-- <div class="banner banner-centered" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%# @location.photo.nil? ? "http://placehold.it/1000x400" : cl_image_path(@location.photo.path) %>');">
  <div class="banner-content">
    <h1><%= @location.title %></h1>
  </div>
</div> -->
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6">
      <div class="location-show-content">
        <div class="description-and-booking">
          <h1><%= @location.title %></h1>
          <h2><%= @location.city %></h2>
          <h3><%= @location.description%></h3>
          &nbsp;
          <h4>Stage de <%= @location.capacity%> personnes</h4>
          <p><em><%= @location.address%></em></p>
          <button type="button" class="btn btn-primary"><%= @location.price %>€</button>

          <% if !(current_user == @location.user) %>
            <div class="new-location-form padded">
              <%= simple_form_for [@location, @booking] do |f| %>
                <%= f.input :date_beginning, as: :string, label: "Date de début", input_html: { class: "datepicker" } %>
                <%= f.input :date_end, as: :string, label: "Date de fin", input_html: { class: "datepicker" } %>
                <%= f.submit "Réserver", class: 'btn btn-primary' %>
              <% end %>
            </div>
          <% end %>
        </div>
        <div id="map" style="width: 100%; height: 400px;">
        </div>
      </div>
    </div>
    <div class="col-sm-6 no-padding-right">
      <div class="location-img">
        <%= cl_image_tag(@location.photo.path) %>
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  </script>
<% end %>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path('carots.JPG') %>);">
  <div class="banner-content">
    <h1>Commencez à faire pousser votre nourriture !</h1>
    <p>Apprenez à cultiver votre propre nourriture dans des lieux uniques, chez vous, seul ou en groupe.</p>
  </div>
</div>


<div class="container paddedh">
<form action="/locations" method="get" class="form-inline" >
  <div class="form-group">
    <select name="urban" id="urban" class="form-control">
      <option selected="selected" value="true">S'initier à l'agriculture urbaine</option>
      <option value="false">Découvrir les bonnes pratiques à la campagne</option>
    </select>
  </div>
  <div class="form-group">
    <input type="text" class= "form-control" placeholder="Ville de votre choix" name="city">
  </div>
  <div class="form-group">
    <select name="capacity" id="capacity" class="form-control">
      <option value="1">1 participant</option>
      <option value="2">2 participants</option>
      <option value="3">3 participants</option>
      <option value="4">4 participants</option>
      <option value="5">5 participants</option>
      <option value="6">6 participants</option>
      <option value="7">7 participants</option>
      <option value="8">8 participants</option>
      <option value="9">9 participants</option>
      <option value="10">10 participants</option></select>
    </select>
  </div>
    <button type="submit" class="btn btn-primary">Rechercher</button>
</form>
</div>

<!-- CARDS -->
<div class="container">
 <div class="row">
    <% @locations.each do |location| %>
    <div class="col-xs-12 col-sm-4 padded">
      <%= render "shared/location_card", location: location %>
    </div>
    <% end  %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_location_card.html.erb
<div class="card card-location" style="background-image: url('<%= cl_image_path location.photo.path %>')">
  <div class="card-category"></div>
  <div class="card-description">
    <h2>
      <%= location.title %>
    </h2>
    <!-- <p><%#= location.description %></p> -->
  </div>
  <!--<img class="card-user avatar" src="user.jpg-->
  <%= link_to "", location_path(location), class: "card-link"%>
</div>

app/views/shared/_navbar.html.erb
<!-- AJOUTER DANS NAVBAR EQUI TO HOTE AIRBNB : Partagez votre savoir-faire (Proposez des stages, des cours particuliers, chez vous à la campagne ou en ville)
 -->

<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logonb.svg" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <!-- <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->
    <%= link_to "Partagez votre savoir-faire", new_location_path, class: "navbar-wagon-item btn" %>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
<!--       <%#= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <%# end %> -->

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <!-- <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div> -->
</div>